spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
hibernate:
  hbm2ddl:
    auto: create
  dialect: org.hibernate.dialect.H2Dialect